apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-orchestrator.fullname" . }}
  labels:
    {{- include "ecommerce-orchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: 34.123.101.193
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce-orchestrator.selectorLabels" . | nindent 4 }}
