production:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "ecommerce_orchestrator_production") %>

development:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "ecommerce_orchestrator_development") %>

test:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "ecommerce_orchestrator_test") %>
